// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AddButton: typeof import('./src/components/AddButton.vue')['default']
		AppHeader: typeof import('./src/components/AppHeader.vue')['default']
		BaseDialog: typeof import('./src/components/Others/BaseDialog.vue')['default']
		CourseCard: typeof import('./src/components/Course/CourseCard.vue')['default']
		CourseListContainer: typeof import('./src/components/CourseList/CourseListContainer.vue')['default']
		CourseSetting: typeof import('./src/components/Course/CourseSetting.vue')['default']
		CreateForm: typeof import('./src/components/CreateForm.vue')['default']
		DeleteButton: typeof import('./src/components/Others/DeleteButton.vue')['default']
		ElBadge: typeof import('element-plus/es')['ElBadge']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
		ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElEmpty: typeof import('element-plus/es')['ElEmpty']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElImage: typeof import('element-plus/es')['ElImage']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
		ElOption: typeof import('element-plus/es')['ElOption']
		ElPopover: typeof import('element-plus/es')['ElPopover']
		ElResult: typeof import('element-plus/es')['ElResult']
		ElSelect: typeof import('element-plus/es')['ElSelect']
		ElTabPane: typeof import('element-plus/es')['ElTabPane']
		ElTabs: typeof import('element-plus/es')['ElTabs']
		ElTag: typeof import('element-plus/es')['ElTag']
		ElTooltip: typeof import('element-plus/es')['ElTooltip']
		FetchComponent: typeof import('./src/components/Others/FetchComponent.vue')['default']
		IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
		IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
		IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
		IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
		IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
		ListItems: typeof import('./src/components/Others/ListItems.vue')['default']
		ProgressForm: typeof import('./src/components/Progress/ProgressForm.vue')['default']
		ProgressItem: typeof import('./src/components/Progress/ProgressItem.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		SearchCompnent: typeof import('./src/components/Others/SearchCompnent.vue')['default']
		SearchComponent: typeof import('./src/components/Others/SearchComponent.vue')['default']
	}
	export interface ComponentCustomProperties {
		vLoading: typeof import('element-plus/es')['ElLoadingDirective']
	}
}
